image: java:8-jdk

# Exported newe gradlehome so that it is inside the build dir
# and can be cached betweend builds. This speeds up the build because
# it dose not require to download a new instance of the gradle wrapper
# every time
before_script:
  - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradlehome"

cache:
  paths:
  - "$CI_PROJECT_DIR/.gradlehome/wrapper/"

run_unit_tests:
  stage: test
  script: ./gradlew test

dist_zip:
  stage: build
  script: ./gradlew distZip
  artifacts:
    paths:
    - build/libs/
    - build/distributions/

deploy_artifactory:
  stage: deploy
  only:
    - tags
  script:
    - ./gradlew -DARTIFACTORY_USERNAME="$ARTIFACTORY_USERNAME" -DARTIFACTORY_PASSWORD="$ARTIFACTORY_PASSWORD" -DARTIFACTORY_URL="$ARTIFACTORY_URL" publish
